### PR TITLE
Exposed url_prefix option to command line of rq-dashboard script

### PR DESCRIPTION
**Pull request by tcorbettclark**
This pull requests exposes --url-prefix as a command line argument so that it is easy to host rq-dashboard behind Nginx with a different URL prefix "out of the box".

Possibly addresses #74.

It also refactors the rq-dashboard script to expose the default PORT and BIND_ADDR to the command line help.

Only tested on Python 2.7.6 under Ubuntu 14.04.2 within a virtualenv.

(I needed the absolute_imports because there are two modules called rq_dashboard: the script and the package).

### CODE REVIEW

**Comment by nvie** [comment]
Thanks, that's useful!

**Comment by tcorbettclark** [comment]
You're welcome!

When do you plan to publish the next update to pypi?

Cheers

**Comment by nvie** [comment]
I'm happy to push it out right now if the current master is working for you. Please let me know. Also, I added a maintainer wanted message to the readme :) https://github.com/nvie/rq-dashboard#wanted-project-maintainer

**Comment by tcorbettclark** [comment]
Hi Vincent

I'm up for being a maintainer. I think the RQ piece is great, and the
architecture of this web front end is exactly how I would have done in too.

The current build works for me. So either please tag and push out, or if
you happy to do so, pass the baton to me and I will have a go.

Tim

**Comment by nvie** [comment]
Hi @tcorbettclark, thanks! That's great news. I've added you as a repo collab here, so you should have write access to this GitHub repo now. Also, can you provide your pypi.python.org username, so I can add you as a package maintainer there? I've added a file [detailing the release process](https://github.com/nvie/rq-dashboard/blob/master/RELEASING.md). Feel free to publish this version of rq-dashboard yourself now :)

**Comment by tcorbettclark** [comment]
Great, thanks Vincent.

My username is tcorbettclark.

Thanks for the build and upload instructions etc.

Do you mind if I use Fabric instead of Make for the build tasks? I've taken
to using it for all my Python work because it keeps everything in one world.

More generally, how involved do you want to be with updates? I would like
to clean up the way the Flask app is invoked. Also peg the package versions
in requirements.txt (leaving setup.py to only mention the required packages
with version info only when specifically needed).

This project looks like a good excuse to get going with tox and start
supporting Python3 (all my current work is standard Python 2.7.6).

All pretty minor housekeeping, at least to start with.

But it's your baby, so I don't want to tread on your toes etc... Please let
me know how you feel about it.

**Comment by tcorbettclark** [comment]
Also, what is "git sha" (in the Makefile)? It does not run for me. Is that
part of your local git configuration?

I'm not very familiar with git as I use hg instead.

Thanks

**Comment by nvie** [comment]
> My username is tcorbettclark.

Thanks! I've added you on PyPI now too, as a package maintainer, so you should be able to upload releases with twine.

> Do you mind if I use Fabric instead of Make for the build tasks? I've taken
> to using it for all my Python work because it keeps everything in one world.

Sure, go for it.

> More generally, how involved do you want to be with updates? I would like
> to clean up the way the Flask app is invoked.

Sounds great. I'd love it if you want to push the project forward, so feel free to make PRs for anything you feel like an improvement. A good flow may be that you take on some work, make a PR, then I'll review it. Also, I'd love it if you'd respond to pull requests, issues, etc.

> Also peg the package versions
> in requirements.txt (leaving setup.py to only mention the required packages
> with version info only when specifically needed).

Personally, I'd only use requirements.txt for top-level projects, not for projects like these. I.e. when you `pip install rq-dashboard`, it should install `rq` and `flask`, so it makes sense to declare those deps in setup.py. The version info requirement for RQ (the `rq>=0.3.8`) stems from a very old update that actually made rq-dashboard break if users did not also upgrade `rq`.

> This project looks like a good excuse to get going with tox and start
> supporting Python3 (all my current work is standard Python 2.7.6).

Yes please!

> But it's your baby, so I don't want to tread on your toes etc... Please let
> me know how you feel about it.

This is all great — thanks for volunteering here :)

**Comment by nvie** [comment]
> Also, what is "git sha" (in the Makefile)? It does not run for me. Is that
> part of your local git configuration?

Oh, oops. This is a local gem I use in many of my projects, I totally forgot about it. For the purpose of this command, you can safely replace it with `git rev-parse` instead, I think. The check is basically a safety net to not accidentally push out the wrong version to PyPI—something I've done in a past too often.

**Pull request merged**
