### PR TITLE
Upgrade rq 1.3.0 -> 1.5.2

### LINKED ISSUE #362: ValueError: time data '' does not match format '%Y-%m-%dT%H:%M:%SZ'
When running rq-dashboard in the latest docker container with

`docker run -p 9181:9181 eoranged/rq-dashboard:v0.6.3`

the **Workers** page cannot load list of workers.

Logs:

```
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/rq_dashboard/web.py", line 101, in _wrapped
    result_dict = f(*args, **kwargs)
  File "/rq_dashboard/web.py", line 535, in list_workers
    workers = sorted(
  File "/rq_dashboard/web.py", line 541, in <genexpr>
    current_job=serialize_current_job(worker.get_current_job()),
  File "/usr/local/lib/python3.8/site-packages/rq/worker.py", line 363, in get_current_job
    return self.job_class.fetch(job_id, self.connection)
  File "/usr/local/lib/python3.8/site-packages/rq/job.py", line 303, in fetch
    job.refresh()
  File "/usr/local/lib/python3.8/site-packages/rq/job.py", line 515, in refresh
    self.restore(data)
  File "/usr/local/lib/python3.8/site-packages/rq/job.py", line 479, in restore
    self.ended_at = str_to_date(obj.get('ended_at'))
  File "/usr/local/lib/python3.8/site-packages/rq/utils.py", line 256, in str_to_date
    return utcparse(as_text(date_str))
  File "/usr/local/lib/python3.8/site-packages/rq/utils.py", line 172, in utcparse
    return datetime.datetime.strptime(string, '%Y-%m-%dT%H:%M:%SZ')
  File "/usr/local/lib/python3.8/_strptime.py", line 568, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
  File "/usr/local/lib/python3.8/_strptime.py", line 349, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data '' does not match format '%Y-%m-%dT%H:%M:%SZ'
```

### PR DESCRIPTION
**Pull request by petlack**
Fixes #362

### CODE REVIEW

**Comment by waldner** [comment]
While this fixes the original issue, I now get:

```
rq-dashboard    | [2020-10-03 14:47:35,257] ERROR in app: Exception on /0/data/jobs/default/failed/11/1.json [GET]
rq-dashboard    | Traceback (most recent call last):
rq-dashboard    |   File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
rq-dashboard    |     response = self.full_dispatch_request()
rq-dashboard    |   File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
rq-dashboard    |     rv = self.handle_user_exception(e)
rq-dashboard    |   File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
rq-dashboard    |     reraise(exc_type, exc_value, tb)
rq-dashboard    |   File "/usr/local/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
rq-dashboard    |     raise value
rq-dashboard    |   File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
rq-dashboard    |     rv = self.dispatch_request()
rq-dashboard    |   File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
rq-dashboard    |     return self.view_functions[rule.endpoint](**req.view_args)
rq-dashboard    |   File "/rq_dashboard/web.py", line 101, in _wrapped
rq-dashboard    |     result_dict = f(*args, **kwargs)
rq-dashboard    |   File "/rq_dashboard/web.py", line 427, in list_jobs
rq-dashboard    |     total_items, jobs = get_queue_registry_jobs_count(
rq-dashboard    |   File "/rq_dashboard/web.py", line 234, in get_queue_registry_jobs_count
rq-dashboard    |     jobs = [serialize_job(job) for job in current_queue_jobs]
rq-dashboard    |   File "/rq_dashboard/web.py", line 234, in <listcomp>
rq-dashboard    |     jobs = [serialize_job(job) for job in current_queue_jobs]
rq-dashboard    |   File "/rq_dashboard/web.py", line 169, in serialize_job
rq-dashboard    |     id=job.id,
rq-dashboard    | AttributeError: 'NoneType' object has no attribute 'id'

```
when I try to look at failed jobs.

**Comment by jmandt** [comment]
@mgax @nvie would one of you guys be able to have a look at the pull request and merge it if this update of rq version is reasonable?

**Comment by mgax** [comment]
> @mgax @nvie would one of you guys be able to have a look at the pull request and merge it if this update of rq version is reasonable?

Hey @jmandt, I haven't used rq-dashboard in years, can't help you there, sorry :)

**Comment by Cybernisk** [comment]
Hi, @jmandt I've got the same problem as @waldner above with `rq==1.5.2` installed inside but with Finished jobs list.

**Comment by Cybernisk** [comment]
I guess I found the reason for the bug. RQ registries are not cleaned. 
My example is that I have 29 jobs in FinishedJobRegistry, but if I count all Redis keys `rq:job:*` it gives me only 8. 
I'm not sure, but it could be because of the old `rq` package I use. Seems that it was fixed in [this MR](https://github.com/rq/rq/pull/1107). I will update all rq and rq-related packages in my project and will see how it goes.

**Pull request closed without merging**
