### PR TITLE
Return password mask for instance-list

### PR DESCRIPTION
**Pull request by mastervolkov**
Need return missed password mask for instance-list

### CODE REVIEW

**Review by cjlapao — APPROVED** [review]

**Comment by maxitg** [comment]
It would be great to merge this and resolve https://github.com/Parallels/rq-dashboard/issues/359.

**Comment by cjlapao** [comment]
@maxitg Are you able to test and confirm this is working? I didn't merge as I was waiting for this confirmation. We are still working on the unit tests to be better

**Comment by maxitg** [comment]
> @maxitg Are you able to test and confirm this is working? I didn't merge as I was waiting for this confirmation. We are still working on the unit tests to be better

Yes. It needs a rebase due to an indentation change, but after that it works. I'm running it as

```console
$ rq-dashboard -u redis://:secret@172.99.251.12:6379
RQ Dashboard version 0.6.0
 * Running on 0.0.0.0:9181
 * Serving Flask app 'rq_dashboard.cli'
 * Debug mode: off
```

On master:

Screenshot 2023-07-14 at 07 55 33

And with this commit:

Screenshot 2023-07-14 at 08 03 27

I also tried adding multiple URLs as

```bash
rq-dashboard -u 'redis://:secret@172.99.251.12:6379' -u 'redis://:passwd@another-host:6379'
```

and they are all masked and I can switch between them using the dropdown.

**Comment by cjlapao** [comment]
@maxitg Cool, I will resolve the merge issues and merge it to master on Monday

**Comment by maxitg** [comment]
> @maxitg Cool, I will resolve the merge issues and merge it to master on Monday

Hi @cjlapao, sorry to bother you again, but could you please help with merging this? It would be greatly appreciated.

**Comment by cjlapao** [comment]
@maxitg 
Could you please fix the conflict? once this passes I will then merge it

**Comment by maxitg** [comment]
> @maxitg Could you please fix the conflict? once this passes I will then merge it

I don't have permissions to push to this PR, but here is another PR after a rebase: https://github.com/Parallels/rq-dashboard/pull/458.

**Comment by cjlapao** [comment]
@maxitg No Problem. closing this one

**Pull request closed without merging**
