### PR TITLE
Add HTTP Basic Auth

### PR DESCRIPTION
**Pull request by jetz**
rq dashboard doesn't have an out-of-the-box auth handler, so I add HTTP Basic Auth for it, we can set username&password, like [supervisor](https://github.com/Supervisor/supervisor), if username or password is ignored, behaves like before.

I think it's useful.

### CODE REVIEW

**Comment by phalgun** [comment]
+1 

This would be a great feature to have. @nvie

**Comment by cosminstefanxp** [comment]
Great work jetz. It would be great to get merged in. Otherwise, I've managed to get things working with the following snippet:

```
# Prepare the authentication for the RQ dashboard
def _basic_http_auth():
    auth = request.authorization
    return auth and auth.password == PASSWORD and auth.username == USERNAME

# And we register it
rq_dashboard.RQDashboard(application, auth_handler=_basic_http_auth)

# NOTE: RQ Dashboard is registered as a blueprint and thus we can setup a Flask error handler for our case.
# When the configured RQ Dashboard auth_handler returns False, a 401 HTTPException is thrown out, so we can intercept
# it. Thus, we setup an error handler for the rq_dashboard blueprint.
def _auth_exception_handler(error):
    return '', 401, {'WWW-Authenticate': 'Basic realm="Login Required"'}

application.error_handler_spec.setdefault('rq_dashboard', {})[401] = _auth_exception_handler
```

**Comment by joostdevries** [comment]
While I agree that this would be nice when using the bundled webapp, I think you can also easily achieve this by setting up a your own minimal Flask app using the blueprint (or using the blueprint in your existing app which might already have authentication built in). 

IMO the command-line app should only be used for testing purposes. It uses `Flask.run` which is **not** meant for production. What do you think @tcorbettclark?

**Comment by tcorbettclark** [comment]
Good point about Flask.run.

I am thinking it would be good to tidy up the presentation of hosting
options. We don't want to prescribe, but we do want to make it easy for
people to use. To a significant extent it boils down to why people use the
dashboard.

I see two representative hosting approaches:

1) Option 1 is to use a command line tool with enough ability to make it
possible to host behind a reverse proxy. For occasional admin use that
seems good to me (despite, and accepting the limitations of the Flask.run
method). It leaves security to the Apache/Nginx/etc level (e.g.
with auth_request through to an existing Flask app), and e.g.
upstart/supervisord/etc to keep it running. The main point is that coupling
to the existing code base is kept very low. I see it as analogous to
supervisord's web interface, which has a questionable cheap and cheerful
authentication (surely not used in production!), but the overall interface
still has it's uses.

2) Option 2 is a deeper integration through a clean code API for inclusion
in an existing set of Flask blueprints.

Clearly people can make their own Option 1 out of Option 2. But if you just
want option 1, we don't want to make people write stub code.

We talk about both of these at the moment, but I think I can make it
clearer. I'll try to have a crack at this over the weekend.

**Comment by tcorbettclark** [comment]
https://github.com/nvie/rq-dashboard/pull/80 prepares the way. I will now add optional basic auth, analogous to how supervisord uses it (cheap and cheerful use).

**Comment by tcorbettclark** [comment]
I've just ported this feature (HTTP Basic Auth for casual security!) across to my pull request #80 in an orthogonal way.

https://github.com/nvie/rq-dashboard/commit/85a3cdec3e1a32851856db93a8930fec4df83379

So if @nvie accepts #80 then this issue can be closed I think.

**Comment by jetz** [comment]
@tcorbettclark great job. hope to be merged soon.

**Comment by nvie** [comment]
Closed by #80

**Pull request closed without merging**
