### PR TITLE
Drop support for EOL Python 2.6

### LINKED ISSUE #145: Drop Python 2.6 support
From [PEP 361](https://www.python.org/dev/peps/pep-0361/#release-lifespan):
Python 2.6.9 is the final security-only source-only maintenance release of the Python 2.6 series. With its release on October 29, 2013, all official support for Python 2.6 has ended. Python 2.6 is no longer being maintained for any purpose.

### PR DESCRIPTION
**Pull request by hugovk**
Fixes #145.

Also a bit of code cleanup.

### CODE REVIEW

**Comment by eoranged** [comment]
Hello, Hugo! Thanks for taking part in rq-dashboard development.
I would have liked to keep Python 2.6 for few more months, till we make some major changes to the code (I know a few companies and people who still use RHEL/Centos 6 and stock Python 2.6, which is supported till November, 2020).
Also the changes regarding replacement of dict calls are completely unrelated to the issue and It is mostly a matter of personal taste, so I prefer to keep `dict` notation.

**Comment by hugovk** [comment]
RHEL/CentOS 6 may be supported until 2020, but Python 2.6 is long unsupported. Those operating systems both support upgrading Python to a secure version, for example via SCL. Still, no rush to merge. 

The dict changes aren't completely unrelated, because they can only be done once 2.6 is dropped.

And they're not changed for personal taste but for performance. See for example https://doughellmann.com/blog/2012/11/12/the-performance-impact-of-using-dict-instead-of-in-cpython-2-7-2/

But I'm happy to ditch that change if you prefer!

**Comment by hugovk** [comment]
Rebased to ditch the dict updates!

**Comment by eoranged** [comment]
Great. Will be merged once we are ready to make a new major release.

**Comment by eoranged** [comment]
I've been talking more with colleagues from other companies and seems like most of them have dropped 2.6 support, so no need to keep waiting any longer.
Thanks for contribution, @hugovk!

**Pull request merged**
