### PR TITLE
Simplify dashboard configuration

### PR DESCRIPTION
**Pull request by eoranged**

### CODE REVIEW

**Comment by coolhacker** [comment]
Now it looks like we don't need a displaying script for instance selector

**Review by coolhacker — APPROVED** [review]

**Comment by eoranged** [comment]
> Now it looks like we don't need a displaying script for instance selector

Why? It is still possible to specify multiple URLs like 

    rq-dashboard -u redis://r1.example.com -u redis://r2.example.com

**Comment by coolhacker** [comment]
Issue #285

**Comment by coolhacker** [comment]
@eoranged if we launch app via rq-dashboard -v, redis url single instance = redis://127.0.0.1 so we don't need to switch display: none via $('#rq-instances').show()

**Pull request merged**
