### PR TITLE
Make job cancel/delete configurable

### PR DESCRIPTION
**Pull request by jlopex**

### CODE REVIEW

**Comment by jlopex** [comment]
@eoranged I extended the PR made by @ ScottSturdivant by allowing this to be configurable and keeping the actual behaviour as is.

**Comment by jlopex** [comment]
@eoranged did you take a look to this PR?

**Comment by eoranged** [comment]
Hello, Javier!
From the first glance everything looks good. I'll try to check It till EOW.

**Comment by eoranged** [comment]
Thanks for the contribution, Javier! Merged.
Sorry for delay, at the moment I have quite busy schedule and unfortunately I'm unable to review changes as quick as I want to.

**Comment by jlopex** [comment]
No worries everybody is busy, so I totally understand you need to take your time. Will you create a new tag? or should we wait for more? Also I think the other two PRs may be closed as this addresses the same needs.

**Comment by eoranged** [comment]
Thanks for reminder!
I'm planning to prepare next release in a few days, just need to review docs, prepare new screenshots, update contributors list and prepare changelog so release looks nicer.

**Pull request merged**
