### PR TITLE
Fix error when using click 8.0.0

### PR DESCRIPTION
**Pull request by ghost**
This line gives the following error when using click 8.0.0
`ValueError: 'default' must be a list when 'multiple' is true.`
see https://github.com/pallets/click/blob/e4301614347d20b90d7fad943a52e9f19bee6be9/src/click/core.py#L2107

### CODE REVIEW

**Review by Houinside — APPROVED** [review]

**Review by Houinside — APPROVED** [review]
when decorator "click" start with option multiple is true, the default must be a list. see source code in click.core,py

**Review by teobouvard — APPROVED** [review]
LGTM

**Review by banduk — APPROVED** [review]

**Review by TimMcCauley — APPROVED** [review]

**Comment by TimMcCauley** [comment]
For those having problems with this issue, I used a fork instead which fixed this in the latest master -

`pip install git+https://github.com/jace/rq-dashboard.git@master`

**Review by 16bc — APPROVED** [review]

**Review by TrevorJamesH — APPROVED** [review]

**Review by gmjohns — APPROVED** [review]

**Comment by ramvenuturumilli** [comment]
@eoranged Could you approve these changes and merge

**Comment by charliemday** [comment]
> pip install git+https://github.com/jace/rq-dashboard.git@master

Thanks @TimMcCauley!

Though `pip install git+https://github.com/jace/rq-dashboard.git@main` (root branch seems to have changed to `main`)

**Comment by cjlapao** [comment]
@jason-rayles-nbcuni , this is already present in the base code

**Pull request closed without merging**
