### PR TITLE
Fix errors from version 0.8.1

### PR DESCRIPTION
**Pull request by jvllmr**
# Description

Unfortunately, I messed up in my PR #495 and introduced erroring code due to inadequate testing.
I fixed the errors and implemented tests for the missing endpoints to catch errors earlier.

I also accidentally stringified None to "None" for exc_info, causing every non-failing job to show a literal "None" in the exc_info block.

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

### Checklist:

- [x] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have run tests (pytest) that prove my fix is effective or that my feature works
- [ ] I have updated the CHANGELOG.md file accordingly
- [x] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by jvllmr** [comment]
I just noticed that the tests are not actually run in GitHub Actions because the actual testing step is always skipped. Is that intended? I can ensure that the tests did succeed on this PR and on the previous PR.

**Comment by jvllmr** [comment]
I have re-enabled the tests for testing with every currently supported python version.

**Comment by cjlapao** [comment]
@jvllmr that was probably due to some issue but the new ones are working and I enabled them as mandatory

merging this and releasing, thanks for the works

**Review by cjlapao — APPROVED** [review]

**Comment by cjlapao** [comment]
@jvllmr this is now released as 0.8.2

**Pull request merged**
